server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Flutter Web 走前端路由，未命中的路径回退到 index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
